replicaCount: 2

image:
  repository: ghcr.io/rudingma/hearthly-api
  tag: sha-4fc4181cd5138c0040fda38c087c7baa4c2b854b
  pullPolicy: IfNotPresent

service:
  port: 3000

ingress:
  enabled: true
  host: api.hearthly.dev

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  PORT: "3000"
