apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: keycloak-s3-credentials
  namespace: {{ .Release.Namespace }}
spec:
  hostAPI: "http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api"
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: hearthly
      secretsScope:
        envSlug: prod
        projectId: "8e2b05b0-c7e7-4e4c-89a7-90bba3e8c705"
        secretsPath: "/"
  managedSecretReference:
    secretName: keycloak-s3-credentials
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: Orphan
    template:
      data:
        S3_ACCESS_KEY: "{{ `{{ .S3_ACCESS_KEY.Value }}` }}"
        S3_SECRET_KEY: "{{ `{{ .S3_SECRET_KEY.Value }}` }}"
