replicaCount: 2

image:
  repository: ghcr.io/rudingma/hearthly-app
  tag: sha-d3f394151381b8c2376863cf1acc137c6a67cced
  pullPolicy: IfNotPresent

service:
  port: 8080

route:
  enabled: true
  host: hearthly.dev
  sectionName: websecure-app
  gateway:
    name: traefik-gateway
    namespace: traefik

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 64Mi

csp:
  apiOrigin: "https://api.hearthly.dev"
  authOrigin: "https://auth.hearthly.dev"
