replicaCount: 2

image:
  repository: ghcr.io/rudingma/hearthly-app
  tag: sha-05bf1dc8e8de0ce816f4b4fadb836201c29650b8
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  enabled: true
  host: hearthly.dev

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 64Mi
