replicaCount: 2

image:
  repository: ghcr.io/rudingma/hearthly-app
  tag: sha-29cbadc1f979957b414d827a17d3a9c5e1eaab3c
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  enabled: true
  host: hearthly.dev

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 64Mi

csp:
  apiOrigin: "https://api.hearthly.dev"
  authOrigin: "https://auth.hearthly.dev"
