apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-ntfy-config
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |
    ntfy:
      baseurl: https://ntfy.sh
      notification:
        priority: |
          status == "firing" && severity == "critical" ? "urgent" :
          status == "firing" ? "high" :
          "default"
        tags:
          - tag: rotating_light
            condition: status == "firing"
          - tag: white_check_mark
            condition: status == "resolved"
        templates:
          title: |
            {{ "{{" }} if eq .Status "resolved" {{ "}}" }}[RESOLVED]{{ "{{" }} else {{ "}}" }}[FIRING]{{ "{{" }} end {{ "}}" }} {{ "{{" }} index .Labels "alertname" {{ "}}" }}
          description: |
            {{ "{{" }} index .Annotations "summary" {{ "}}" }}
