apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ntfy-topic-secret
  namespace: {{ .Release.Namespace }}
spec:
  hostAPI: "http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api"
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: hearthly
      secretsScope:
        envSlug: prod
        projectId: "8e2b05b0-c7e7-4e4c-89a7-90bba3e8c705"
        secretsPath: "/"
  managedSecretReference:
    secretName: ntfy-topic
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: Orphan
    template:
      data:
        NTFY_TOPIC: "{{ `{{ .NTFY_TOPIC.Value }}` }}"
