apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hearthly-db
  namespace: hearthly
spec:
  instances: 1

  postgresql:
    parameters:
      shared_buffers: "128MB"
      max_connections: "50"

  storage:
    size: 10Gi
    storageClass: hcloud-volumes

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "1"

  bootstrap:
    initdb:
      database: hearthly
      owner: hearthly
